version: "3.3"
services:

  postgres:
    hostname: postgres
    container_name: postgres-recipes
    image: postgres:12-alpine
    restart: always
    ports:
      - "9000:5432"
    environment:
      POSTGRES_DB: recipes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
